### ISSUE TITLE
Commit reverted pull commits

### ISSUE THREAD

**Issue by danbst** [mikeizbicki/subhask#10]
commit https://github.com/mikeizbicki/subhask/commit/dca6ac0423e6b38c481a81cc7fc3ac7556f58288 reverted at least f7dab6b4c05fd355bb7664197bf9494e3e248487 and 97de0c8b6bc4c73f9748ca0e35dfaadb8b214e10 (don't know about others)

**Comment by mikeizbicki** [comment]
Thanks for pointing that out, it should be fixed now.  I wonder what I did to git to undo those commits...
