### ISSUE TITLE
examples/example0002-monad-instances-for-set.lhs says that `Set` is a `Functor`

### ISSUE THREAD

**Issue by cdepillabout** [mikeizbicki/subhask#16]
The recently updated version of `examples/example0002-monad-instances-for-set.lhs` says that `Set` should be a `Functor`:

https://github.com/mikeizbicki/subhask/blob/master/examples/example0002-monad-instances-for-set.lhs#L37

However, there are no instances of `Functor` for `Set`.

Also, as far as I can tell, there are no valid instances of `Functor` in either the category `Hask` or the category `OrdHask`.  Is there some subcategory of `Hask` where `Set` is a valid `Functor`?

Here are two possible ways I can see to solve this:

1.  Change the documentation.  I could send a pull request taking out the line in question from `example0002-monad-instances-for-set.lhs`.
2.  Implement a `Functor` instance for `Set`.  If there is a category that has a valid `Functor` instance for `Set`, I could implement it and send a pull request.

Let me know what you want me to do (if anything).

**Comment by mikeizbicki** [comment]
Whoops!  You're right, I misspoke about that, so the documentation needs fixing.

**Comment by cdepillabout** [comment]
Fixed in #17.
