### ISSUE TITLE
Remove dependency from outside C libraries

### ISSUE THREAD

**Issue by varosi** [mikeizbicki/subhask#18]
This is a feature request. 
Currently it depend on C libraries like BLAS and LAPACK. It is harder to build the project because of that. And if there are no C library dependencies it will be more portable.

**Comment by mikeizbicki** [comment]
I agree with this in principle, but in practice this isn't possible.  At least yet.  SubHask needs linear algebra support from something, and the best existing solution is hmatrix, which requires BLAS and LAPACK.  If someone else were to writing SubHask bindings to a pure haskell implementation of linear algebra (e.g. bed-and-breakfast), then I'd be happy to factor out all of the BLAS and LAPACK stuff and put them in a separate library.  But this would be a lot of work, and I'm not sure the gain would be worth it.

**Comment by varosi** [comment]
Yes, you're right. May be hmatrix itself should be cleaned from C dependencies.
