### ISSUE TITLE
Upgrade stackage resolver to 5.1

### ISSUE THREAD

**Issue by alexanderkjeldaas** [mikeizbicki/subhask#27]
The lts-3.3 resolver is 4 months old.

**Comment by mikeizbicki** [comment]
Do you have any concrete reasons for wanting to upgrade to a newer lts?  I don't see the value.

**Comment by aupiff** [comment]
@tonyday567 said:

> The main reason for moving to the current version of lts is to be able to include subhask in other projects. An example is ihaskell - I would like to be able to include subhask in an ipython notebook but it proved impossible to drop that ecosystem back to lts-3.3 (I tried).

I'd like to upgrade lts versions for a similar reason. Also, is there a reason why there are explicit package version numbers in `subhask.cabal` given that it already uses stack?

**Comment by alexanderkjeldaas** [comment]
@mikeizbicki my reason is that I wanted to use HLearn.
I don't want to fiddle with cabal build problems, so I stick with stackage.
I generally use the latest nightly version of stackage, if possible, so I have the freshest possible set of libraries, without any build issues.

**Comment by mikeizbicki** [comment]
Fixed by #30.  Let me know if you run into problems.
