### ISSUE TITLE
cabal install failed

### ISSUE THREAD

**Issue by montagy** [mikeizbicki/subhask#3]
Failed to install subhask-0.1.0.0
Build log ( /home/montagy/.cabal/logs/subhask-0.1.0.0.log ):
Configuring subhask-0.1.0.0...
Building subhask-0.1.0.0...
Preprocessing library subhask-0.1.0.0...
[ 1 of 39] Compiling SubHask.TemplateHaskell.Common ( src/SubHask/TemplateHaskell/Common.hs, dist/build/SubHask/TemplateHaskell/Common.o )
/tmp/ghc14409_0/ghc14409_8.s: Assembler messages:

/tmp/ghc14409_0/ghc14409_8.s:24:0:
     Error: can't resolve `.rodata' {.rodata section} - `subhazu5cvqvHkFXU40mzz2nyzz00Qh_SubHaskziTemplateHaskellziCommon_apply2varlist1_info$def' {.text section}

/tmp/ghc14409_0/ghc14409_8.s:43:0:
     Error: can't resolve `.rodata' {.rodata section} - `subhazu5cvqvHkFXU40mzz2nyzz00Qh_SubHaskziTemplateHaskellziCommon_apply2varlist_info$def' {.text section}
cabal: Error: some packages failed to install:
subhask-0.1.0.0 failed during the building phase. The exception was:
ExitFailure 1

never seen this error before
ghc-7.10.1 cabal-1.22.3

**Comment by mikeizbicki** [comment]
Since you're on ghc 7.10, you'll need to use the ghc 7.10 branch.

**Comment by montagy** [comment]
yes.i use ghc 7.10branch .i am not familar with TH,the error is odd.
BTW,ubuntu 14.04

**Comment by mikeizbicki** [comment]
If I'm reading the error message correctly, the problem is in the generated assembly.  What version of llvm are you using, and what OS are you on?

**Comment by montagy** [comment]
ubuntu 14.04.2
llvm 3.4

**Comment by mikeizbicki** [comment]
ghc 7.8 requires llvm 3.4, but ghc 7.10 requires llvm 3.5.  I'm pretty sure that's the problem.  I'm surprised ghc didn't throw a warning somewhere about that.

**Comment by montagy** [comment]
after install llvm-3.5,and change the ghc lib settings file
("LLVM llc command", "llc-3.5"),
("LLVM opt command", "opt-3.5")  
i get this error
Preprocessing library subhask-0.1.0.0...
[ 6 of 39] Compiling SubHask.Mutable  ( src/SubHask/Mutable.hs, dist/build/SubHask/Mutable.o )

src/SubHask/Mutable.hs:56:32:
    Not in scope: type constructor or class ‘PrimBase’
src/SubHask/Mutable.hs:61:24:
    Not in scope: type constructor or class ‘PrimBase’
so i think you use primitive 0.6
after change the cabal file primitive == 0.6
semigroups == 0.16.2.2 (the latest semigroups,for not reinstall some package)
install successed.
thanks for your help,and your great work
