### ISSUE TITLE
OSX hmatrix linking

### ISSUE THREAD

**Issue by tonyday567** [mikeizbicki/subhask#42]
On OSX 10.11.3, I get the error below at the end of `stack ghci :TestSuite-Unoptimized`.  I half expect I need to point at gcc rather than clang, but is this familiar to anyone?

subhask-0.1.1.0: build (lib + test)
Preprocessing library subhask-0.1.1.0...
ld: warning: directory not found for option '-L/opt/local/lib/'
In-place registering subhask-0.1.1.0...
Preprocessing test suite 'TestSuite-Unoptimized' for subhask-0.1.1.0...
Linking .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/TestSuite-Unoptimized/TestSuite-Unoptimized ...
ld: warning: directory not found for option '-L/opt/local/lib/'
Undefined symbols for architecture x86_64:
  "___ieee_divdc3", referenced from:
      _mapValC in libHShmatrix-0.17.0.1-JWP6dOY4q7oAh3GMbxK0jp.a(vector-aux.o)
      _zipC in libHShmatrix-0.17.0.1-JWP6dOY4q7oAh3GMbxK0jp.a(vector-aux.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
             
--  While building package subhask-0.1.1.0 using:
      /Users/tonyday/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.5.0 build lib:subhask test:TestSuite-Unoptimized --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
Warning: build failed, but optimistically launching GHCi anyway
The following GHC options are incompatible with GHCi and have not been passed to it: -O0
Using main module: 1. Package `subhask' component test:TestSuite-Unoptimized with main-is file: /Users/tonyday/git/subhask/test/TestSuite.hs
Configuring GHCi with the following packages: subhask
Progress: 1/2GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package subhask-0.1.1.0
    (use -v for more information)

**Comment by mikeizbicki** [comment]
Did your edits in #44 explain how to fix this?  I noticed you added OSX specific instructions.

**Comment by tonyday567** [comment]
Can't reproduce.  I've gone through a few different llvm's in testing, so was probably a wrong one and will close this.
