### ISSUE TITLE
build failure with ghc-7.8.4

### ISSUE THREAD

**Issue by mwotton** [mikeizbicki/subhask#5]
src/SubHask/Algebra/Ord.hs:55:1:
    Conflicting family instance declarations:
      Mutable m (WithPreludeOrd a0)
        -- Defined at src/SubHask/Algebra/Ord.hs:55:1
      Mutable -- Defined at src/SubHask/Mutable.hs:48:18
cabal: Error: some packages failed to install:
subhask-0.1.0.0 failed during the building phase. The exception was:
ExitFailure 1

**Comment by mikeizbicki** [comment]
Thanks for the report.  I was using ghc 7.8.2 on the master branch and I didn't have problems.  Maybe something's changed with 7.8.4 that's causing this?  Either way, I've upgrade to 7.10.1 now and I don't have 7.8 available to reproduce the issue.  I'll be mergeing the 7.10 branch into master pretty soon.

**Comment by mwotton** [comment]
can confirm that 7.8.2 works ok. I wonder what changed...
