### ISSUE TITLE
BLAS / LAPACK on Mac

### ISSUE THREAD

**Issue by hdmetor** [mikeizbicki/subhask#50]
Trying going through the `README` and I noticed that it mentions the installation of BLAS / LAPACK for Mac too.
 
- on Mac they come pre-installed (at least from 10.9). It is called the [Accelerate Framework](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man7/Accelerate.7.html)

- I think that the `brew` instructions are now outdated. This is the error I receive

        $ brew install libblas-dev liblapack-dev
        Error: No available formula with the name "libblas-dev"
        ==> Searching for similarly named formulae...
        Error: No similarly named formulae found.
        ==> Searching taps...
        Error: No formulae found in taps.

I just finished the testing via `stack test --bench` and I didn't get any error.

**Comment by mikeizbicki** [comment]
I don't have a Mac, so I can't test the install instructions to say for sure.  But if you edit the readme with updated instructions, I'll accept update.

**Comment by hdmetor** [comment]
Will do. Tests are running fine, but I am having problems with the examples. As soon as I figure this out, I will send a PR your way

**Comment by hdmetor** [comment]
I believe that is a very basic question, but how do you run the examples? I run `stack test --bench` without any problems, so the project is build locally. I have tried 

    $ ghc examples/example0001-polynomials.lhs

    examples/example0001-polynomials.lhs:7:10:
        Could not find module ‘SubHask’
        Use -v to see a list of the files searched for.

    examples/example0001-polynomials.lhs:8:10:
        Could not find module ‘SubHask.Category.Polynomial’
        Use -v to see a list of the files searched for.

and 

    $ ghc examples/example0001-polynomials.lhs -i src/SubHask.hs

which gives me even more errors

**Comment by mikeizbicki** [comment]
The examples are part of the test suite, so if `stack test` is successful, then the examples were successful.  Does that answer your question?
